// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1R8svTrqkQ1JwVlBNfsaE7tNjgMl4_Rw',
    appId: '1:70178944183:web:e7f8996fc990e2f38cc932',
    messagingSenderId: '70178944183',
    projectId: 'chatterbox-891ae',
    authDomain: 'chatterbox-891ae.firebaseapp.com',
    databaseURL: 'https://chatterbox-891ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-891ae.appspot.com',
    measurementId: 'G-1KT3TDV67F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAO4CzJp6-FKxkPENSBh7lwVwL_jboZsU',
    appId: '1:70178944183:android:f88496075c1906308cc932',
    messagingSenderId: '70178944183',
    projectId: 'chatterbox-891ae',
    databaseURL: 'https://chatterbox-891ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-891ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCzgGjXZVht5m70mcsxq0pCxGQCufcJfY',
    appId: '1:70178944183:ios:943a4d5bcab409528cc932',
    messagingSenderId: '70178944183',
    projectId: 'chatterbox-891ae',
    databaseURL: 'https://chatterbox-891ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterbox-891ae.appspot.com',
    androidClientId: '70178944183-0vmstuth8k6tlt7sn0t3cl91890f0eh3.apps.googleusercontent.com',
    iosClientId: '70178944183-4232pldalpnqa49hkfmp74hcetaoenf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCzgGjXZVht5m70mcsxq0pCxGQCufcJfY',
    appId: '1:70178944183:ios:3aa4262ebff095cc8cc932',
    messagingSenderId: '70178944183',
    projectId: 'chatterbox-891ae',
    storageBucket: 'chatterbox-891ae.appspot.com',
    iosBundleId: 'com.example.chatterbox.RunnerTests',
    databaseURL: 'https://chatterbox-891ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    androidClientId: '70178944183-0vmstuth8k6tlt7sn0t3cl91890f0eh3.apps.googleusercontent.com',
    iosClientId: '70178944183-qsseijtrho23g1k6luo2q9tot9er0335.apps.googleusercontent.com',
  );
}
